### ISSUE TITLE
Seguir client addFollower does not use timestamp

### ISSUE THREAD

**Issue by dmorgantini** [cliftonc/seguir#12]
Since timestamp is not in the server api, should we remove it from the client?

https://github.com/cliftonc/seguir/blob/master/client/index.js#L364

**Comment by cliftonc** [comment]
Bit of an oversight - turns out all of the api's that take timestamp as an input on the client actually ignore it ... 

https://github.com/cliftonc/seguir/blob/master/server/index.js#L389
https://github.com/cliftonc/seguir/blob/master/server/index.js#L616
https://github.com/cliftonc/seguir/blob/master/server/index.js#L527

We should remove timestamp from all of the client APIs.

**Comment by cliftonc** [comment]
Resolved by https://github.com/cliftonc/seguir/commit/c5bb6ffd80db39c0d2c35a2c0065dfd4d9c8eee3
