### ISSUE TITLE
Follower list time bomb

### ISSUE THREAD

**Issue by cliftonc** [cliftonc/seguir#31]
~~https://github.com/cliftonc/seguir/blob/master/api/follow/index.js#L149~~ (Outdated line)

Follower list is not paginated and should be.

**Comment by dmorgantini** [comment]
I'm wondering about pagination for the followers - while I agree that it should be done (I'm currently trying to figure out Cassandra) I think another change that should be done is that the follower count should actually be part of the user rather than it's own table.  This would eliminate the n+1 calls that ~~cripple~~ slow down cassandra when somebody views the followers page.

**Comment by cliftonc** [comment]
The alternative is that we don't show the number of followers for every single user listed on the follower page ...
